### Item Based CF

In [3]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import pandas as pd 
header = ['user_id','item_id','rating','timestamp']
dataset = pd.read_csv(r'C:\Users\Madhukar\OneDrive\Pictures\ml-100k\ml-100k\u.data',sep = '\t',names = header)
print(dataset.head())

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596


#### We transform the dataset into a matrix where each row represents the user and column represents the item.
#### The n_users defines the number of users whereas n_items defines the number of items in the dataset. The loop iterates through each row of the dataframe and extracts ratings from it to form the user-item rating matrix.

In [5]:
n_users = dataset.user_id.unique().shape[0]
n_items = dataset.item_id.unique().shape[0]
n_items = dataset['item_id'].max()
A = np.zeros((n_users,n_items))
for line in dataset.itertuples():
    A[line[1]-1,line[2]-1] = line[3]
print("Original rating matrix : ",A)

Original rating matrix :  [[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


#### The MovieLens dataset consists of ratings on a scale of 1-5 where 1 represents the lowest rating while 5 represents the highest rating.
#### The below code converts the MovieLens dataset into the binary MovieLens dataset. We have considered items whose ratings are greater or equal to 3 being liked by the user and others being disliked by the user. As we are only considerate about the liking of users, making ratings less than 3 as 0 would not impact the recommendation process.
#### Further, users rarely provide ratings to items which results in a sparse dataset. The considered MovieLens dataset is 93.7% sparse which is further being increased by converting the matrix into a binary matrix. Therefore, to save the memory, we convert the dense rating matrix into a sparse matrix using the csr_matrix() function.

In [6]:
csr_sample = csr_matrix(A)
print(csr_sample)


  (0, 0)	5.0
  (0, 1)	3.0
  (0, 2)	4.0
  (0, 3)	3.0
  (0, 4)	3.0
  (0, 5)	5.0
  (0, 6)	4.0
  (0, 7)	1.0
  (0, 8)	5.0
  (0, 9)	3.0
  (0, 10)	2.0
  (0, 11)	5.0
  (0, 12)	5.0
  (0, 13)	5.0
  (0, 14)	5.0
  (0, 15)	5.0
  (0, 16)	3.0
  (0, 17)	4.0
  (0, 18)	5.0
  (0, 19)	4.0
  (0, 20)	1.0
  (0, 21)	4.0
  (0, 22)	4.0
  (0, 23)	3.0
  (0, 24)	4.0
  :	:
  (942, 738)	4.0
  (942, 755)	2.0
  (942, 762)	4.0
  (942, 764)	3.0
  (942, 784)	2.0
  (942, 793)	3.0
  (942, 795)	3.0
  (942, 807)	4.0
  (942, 815)	4.0
  (942, 823)	4.0
  (942, 824)	3.0
  (942, 830)	2.0
  (942, 839)	4.0
  (942, 927)	5.0
  (942, 940)	1.0
  (942, 942)	5.0
  (942, 1010)	2.0
  (942, 1027)	2.0
  (942, 1043)	3.0
  (942, 1046)	2.0
  (942, 1066)	2.0
  (942, 1073)	4.0
  (942, 1187)	3.0
  (942, 1227)	3.0
  (942, 1329)	3.0


#### Compute similarity between items of csr_sample using cosine similarity as shown below:

In [7]:
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=3, n_jobs=-1)
knn.fit(csr_sample)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=3)

#### Once, the similarity between items is computed, the final step is to generate recommendations for the target user. Here, we are generating recommendations for the user_id: 1.

#### We generate recommendations for user_id:1 based on 20 items being liked by him. So, we first get the 20 items being liked/consumed by the user as shown below:

In [8]:
dataset_sort_des = dataset.sort_values(['user_id', 'timestamp'], ascending=[True, False])
filter1 = dataset_sort_des[dataset_sort_des['user_id'] == 1].item_id
filter1 = filter1.tolist()
filter1 = filter1[:20]
print("Items liked by user: ",filter1)

Items liked by user:  [74, 102, 256, 5, 171, 111, 242, 189, 32, 209, 270, 18, 6, 244, 221, 129, 20, 271, 272, 255]


#### Next, for each item being liked by the user1, we recommend 2 similar items. The number of similar items to be recommended can vary depending on the need of the system.

In [9]:
distances1=[]
indices1=[]
for i in filter1:
    distances, indices = knn.kneighbors(csr_sample[i],n_neighbors=3)
    indices = indices.flatten()
    indices= indices[1:]
    indices1.extend(indices)
print("Items to be recommended: ",indices1)

Items to be recommended:  [517, 356, 230, 758, 883, 893, 473, 17, 436, 311, 615, 855, 105, 614, 103, 163, 501, 510, 642, 406, 473, 536, 578, 475, 649, 312, 688, 778, 681, 108, 275, 681, 365, 813, 685, 297, 719, 865, 373, 331]


### Assignment - Replace movie_id with corresponding movie_name from given file and build the model

## User Based

In [13]:
import pandas as pd
animes = pd.read_csv(r'C:\Users\Madhukar\OneDrive\Pictures\archive1\anime.csv')
ratings = pd.read_csv(r'C:\Users\Madhukar\OneDrive\Pictures\archive1\rating.csv')

In [14]:
ratings = ratings[ratings.rating != -1]
ratings.head()

user_id  anime_id  rating
47         1      8074      10
81         1     11617      10
83         1     11757      10
101        1     15451      10
153        2     11771      10

In [15]:
animes.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [24]:
# # number of ratings
# print(len(ratings))
# # 6337241
# # number of users
# print(len(ratings['user_id'].unique()))
# # 69600
# # number of unique animes (in anime list, not ratings)
# print(len(animes['anime_id'].unique()))
# #=> 11200
# # avg number of anime rated per user
# import statistics
ratings_per_user = ratings.groupby('user_id')['rating'].count()
# print(statistics.mean(ratings_per_user.tolist()))
# #=> 91.05231321839081
# # distribution of ratings per user
# # (we may want to exclude users without many data points)
# # import matplotlib.pyplot as plt
# # %matplotlib inline
# # ratings_per_user.hist(bins=20, range=(0,500))

In [25]:
# # avg number of ratings given per anime
ratings_per_anime = ratings.groupby('anime_id')['rating'].count()
 #statistics.mean(ratings_per_anime.tolist())
#638.3843054296364
#distribution of ratings per anime
#import matplotlib.pyplot as plt
# %matplotlib inline
 #ratings_per_anime.hist(bins=20, range=(0,2500))

#### In user-based collaborative filtering, vectors representing users are essentially lists of the ratings they’ve given. So the more anime in our universe, the more dimensionality per user.

#### Let's reduce the amount of data to crunch by removing anime that hasn’t been rated by many users. Make a list of anime to keep based on id.

In [26]:
# counts of ratings per anime as a df
ratings_per_anime_df = pd.DataFrame(ratings_per_anime)
# remove if < 1000 ratings
filtered_ratings_per_anime_df = ratings_per_anime_df[ratings_per_anime_df.rating >= 1000]
# build a list of anime_ids to keep
popular_anime = filtered_ratings_per_anime_df.index.tolist()

In [27]:
# counts ratings per user as a df
ratings_per_user_df = pd.DataFrame(ratings_per_user)
# remove if < 500
filtered_ratings_per_user_df = ratings_per_user_df[ratings_per_user_df.rating >= 500]
# build a list of user_ids to keep
prolific_users = filtered_ratings_per_user_df.index.tolist()

In [28]:
filtered_ratings = ratings[ratings.anime_id.isin(popular_anime)]
filtered_ratings = ratings[ratings.user_id.isin(prolific_users)]
len(filtered_ratings)

1005314

In [33]:
rating_matrix = filtered_ratings.pivot_table(index='user_id', columns='anime_id', values='rating')
# replace NaN values with 0
rating_matrix = rating_matrix.fillna(0)
# display the top few rows
rating_matrix

anime_id  1      5      6      7      8      15     16     17     18     \
user_id                                                                   
226         8.0    0.0    8.0    0.0    0.0    0.0    0.0    0.0    0.0   
271         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
294         7.0    7.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
392         7.0    0.0    7.0    0.0    0.0    0.0    0.0    0.0    7.0   
446         9.0    8.0    9.0    0.0    0.0    0.0    0.0    0.0    0.0   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
73362      10.0   10.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
73378       9.0    9.0    0.0    0.0    0.0    0.0    0.0    0.0    8.0   
73395      10.0    9.0   10.0    0.0    0.0    9.0    0.0    0.0    0.0   
73499       9.0    0.0    9.0    0.0    0.0   10.0    0.0    0.0    0.0   
73502       0.0    0.0    0.0    9.0    0.0    0.0   10.0    0.0    0.0   

anime_id  19     ...  34238  34239  34240  34252  34283  34324  34325  34349  \
user_id          ...                                                           
226         0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
271         0.0  ...    0.0    0.0   10.0    0.0    0.0    0.0    0.0    0.0   
294         0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
392         0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
446        10.0  ...    0.0    0.0    9.0    0.0    0.0    0.0    0.0    0.0   
...         ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
73362       0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
73378       0.0  ...    0.0    0.0    9.0    0.0    0.0    0.0    0.0    0.0   
73395       0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
73499       0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
73502       0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

anime_id  34367  34475  
user_id                 
226         0.0    0.0  
271         0.0    0.0  
294         0.0    0.0  
392         0.0    0.0  
446         0.0    0.0  
...         ...    ...  
73362       0.0    0.0  
73378       0.0    0.0  
73395       0.0    0.0  
73499       0.0    0.0  
73502       0.0    0.0  

[1365 rows x 9591 columns]

In [34]:
from sklearn.metrics.pairwise import cosine_similarity
import operator
def similar_users(user_id, matrix, k=3):
    # create a df of just the current user
    user = matrix[matrix.index == user_id]
    
    # and a df of all other users
    other_users = matrix[matrix.index != user_id]
    
    # calc cosine similarity between user and each other user
    similarities = cosine_similarity(user,other_users)[0].tolist()
    
    # create list of indices of these users
    indices = other_users.index.tolist()
    
    # create key/values pairs of user index and their similarity
    index_similarity = dict(zip(indices, similarities))
    
    # sort by similarity
    index_similarity_sorted = sorted(index_similarity.items(), key=operator.itemgetter(1))
    index_similarity_sorted.reverse()
    
    # grab k users off the top
    top_users_similarities = index_similarity_sorted[:k]
    users = [u[0] for u in top_users_similarities]
    
    return users


In [45]:
current_user = 226
# try it out
similar_user_indices = similar_users(current_user, rating_matrix)
print(similar_user_indices)

[30773, 39021, 45603]


#### The function to return the 5 top recommended anime

In [46]:
def recommend_item(user_index, similar_user_indices, matrix, items=5):
    
    # load vectors for similar users
    similar_users = matrix[matrix.index.isin(similar_user_indices)]
    # calc avg ratings across the 3 similar users
    similar_users = similar_users.mean(axis=0)
    # convert to dataframe so its easy to sort and filter
    similar_users_df = pd.DataFrame(similar_users, columns=['mean'])
    
    
    # load vector for the current user
    user_df = matrix[matrix.index == user_index]
    # transpose it so its easier to filter
    user_df_transposed = user_df.transpose()
    # rename the column as 'rating'
    user_df_transposed.columns = ['rating']
    # remove any rows without a 0 value. Anime not watched yet
    user_df_transposed = user_df_transposed[user_df_transposed['rating']==0]
    # generate a list of animes the user has not seen
    animes_unseen = user_df_transposed.index.tolist()
    
    # filter avg ratings of similar users for only anime the current user has not seen
    similar_users_df_filtered = similar_users_df[similar_users_df.index.isin(animes_unseen)]
    # order the dataframe
    similar_users_df_ordered = similar_users_df.sort_values(by=['mean'], ascending=False)
    # grab the top n anime   
    top_n_anime = similar_users_df_ordered.head(items)
    top_n_anime_indices = top_n_anime.index.tolist()
    # lookup these anime in the other dataframe to find names
    anime_information = animes[animes['anime_id'].isin(top_n_anime_indices)]
    
    return anime_information #items

In [47]:
# try it out
recommend_item(226, similar_user_indices, rating_matrix)

anime_id                    name  \
6       11061  Hunter x Hunter (2011)   
39      12365     Bakuman. 3rd Season   
87      10030     Bakuman. 2nd Season   
131      4224               Toradora!   
184      7674                Bakuman.   

                                       genre type episodes  rating  members  
6    Action, Adventure, Shounen, Super Power   TV      148    9.13   425855  
39           Comedy, Drama, Romance, Shounen   TV       25    8.71   133620  
87           Comedy, Drama, Romance, Shounen   TV       25    8.53   151561  
131   Comedy, Romance, School, Slice of Life   TV       25    8.45   633817  
184                 Comedy, Romance, Shounen   TV       25    8.35   246899